<?php
echo 'PHP_SELF:'.$_SERVER['PHP_SELF'].PHP_EOL;
echo 'DOCUMENT_ROOT:'.$_SERVER['DOCUMENT_ROOT'].PHP_EOL;
echo 'SCRIPT_FILENAME:'.$_SERVER['SCRIPT_FILENAME'].PHP_EOL;
echo 'SCRIPT_NAME:'.$_SERVER['PHP_SELF'].PHP_EOL;